server {
  listen 80;
  client_max_body_size 10m;
  root /home/isucon/private_isu/webapp/public/;

  access_log /var/log/nginx/access.log ltsv;

  location ~* \.(css|js|gif|png|jpg|jpeg|ico)$ {
    expires 1h;
    try_files $uri @app;
  }

  location @app {
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://app;
  }

  location / {
    proxy_set_header Host $host;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_pass http://app;
  }
}
