apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: mysql:3306
    user: root
    jsonData:
      database: isuconp
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
    secureJsonData:
      password: root