log_format ltsv "time:$time_local"
  "\thost:$remote_addr"
  "\tmethod:$request_method"
  "\turi:$request_uri"
  "\tstatus:$status"
  "\tsize:$body_bytes_sent"
  "\treqtime:$request_time"
  "\tapptime:$upstream_response_time"
  "\tupstream:$upstream_addr"
  "\tcache:$upstream_cache_status";

server {
  listen 80;

  client_max_body_size 10m;
  root /public/;

  access_log /var/log/nginx/access_ltsv.log ltsv;

  location / {
    proxy_set_header Host $host;
    proxy_pass http://app:8080;
  }
}
