source 'https://rubygems.org'

gem 'rails', '4.2.5'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'sidekiq'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem 'chartkick'
gem 'bootstrap-sass', '~> 3.3.6'

gem 'devise'
gem 'bcrypt', '~> 3.1.7'

# webserver
gem 'puma'

group :production do
  gem 'mysql2'
end

group :development, :test do
  gem 'sqlite3'
  gem 'byebug'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'capistrano-sidekiq'
  gem 'capistrano-rails'
  gem 'capistrano3-puma'
end

